sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t 13579246789/react-test -f ./client-react/Dockerfile.dev ./client-react

script:
  - docker run -e CI=true 13579246789/react-test npm test

after_success:
  - docker build -t 13579246789/multi-client ./client-react
  - docker build -t 13579246789/multi-nginx ./nginx
  - docker build -t 13579246789/multi-server ./server
  - docker build -t 13579246789/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push 13579246789/multi-client
  - docker push 13579246789/multi-nginx
  - docker push 13579246789/multi-server
  - docker push 13579246789/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-006507480490"
  bucket_path: "multi-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
